### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by danmincu** [primefaces/sakai-ng#30]
attempting to run `npm test` throws the following error
```
Error during loading: Uncaught TypeError: __webpack_require__(...).context is not a function in http://localhost:9876/_karma_webpack_/main.js line 22
```
I tried on Windows 11 with

Angular CLI: 15.2.9
Node: 18.16.0
Package Manager: yarn 1.22.19
OS: win32 x64
Angular: 15.2.9

```

$ npm test

> sakai-ng@15.0.0 test
> ng test

⠋ Generating browser application bundles (phase: setup)...    TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browerslist configuration. For more information, see https://angular.io/guide/build#configuring-browser-compatibility
    NOTE: You can set the "target" to "ES2022" in the project's tsconfig to remove this warning.
✔ Browser application bundle generation complete.
14 07 2023 01:43:39.183:WARN [karma]: No captured browser, open http://localhost:9876/
14 07 2023 01:43:39.192:INFO [karma-server]: Karma v6.3.20 server started at http://localhost:9876/
14 07 2023 01:43:39.192:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
14 07 2023 01:43:39.194:INFO [launcher]: Starting browser Chrome
14 07 2023 01:43:39.708:INFO [Chrome 114.0.0.0 (Windows 10)]: Connected on socket NzxaOOPXS1SvRFBeAAAB with id 50648254
Chrome 114.0.0.0 (Windows 10) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: __webpack_require__(...).context is not a function
  TypeError: __webpack_require__(...).context is not a function
      at Object.4289 (http://localhost:9876/_karma_webpack_/webpack:/src/test.ts:24:25)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9876/_karma_webpack_/main.js:48:48)
      at http://localhost:9876/_karma_webpack_/main.js:49:54
      at Function.__webpack_require__.O (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/chunk loaded:23:1)
      at http://localhost:9876/_karma_webpack_/main.js:50:56
      at webpackJsonpCallback (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/jsonp chunk loading:34:1)
      at http://localhost:9876/_karma_webpack_/main.js:1:69
Chrome 114.0.0.0 (Windows 10): Executed 0 of 0 ERROR (0 secs / 0 secs)
Chrome 114.0.0.0 (Windows 10) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: __webpack_require__(...).context is not a function
  TypeError: __webpack_require__(...).context is not a function
      at Object.4289 (http://localhost:9876/_karma_webpack_/webpack:/src/test.ts:24:25)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9876/_karma_webpack_/main.js:48:48)
      at http://localhost:9876/_karma_webpack_/main.js:49:54
      at Function.__webpack_require__.O (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/chunk loaded:23:1)
      at http://localhost:9876/_karma_webpack_/main.js:50:56
      at webpackJsonpCallback (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/jsonp chunk loading:34:1)

```

**Comment by danmincu** [comment]
Actually this is happeining because the author upgraded to 15 without re-testing.
One can run the 
`ng update @angular/cli --from 14 --to 15 --migrate-only`
that will automatically update the `test.ts` file.

Or we just need to manually remove the context from the `test.ts` file 
```
// This file is required by karma.conf.js and loads recursively all the .spec and framework files

import 'zone.js/testing';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting(),
);

```
